name: ClassPatcher
version: '${project.version}'
main: de.crazydev22.classpatcher.ClassPatcher
api-version: '1.20'
load: STARTUP
authors: [CrazyDev22]

commands:
  cprl:
    permission: "classpatcher.reload"